# Generated by Django 2.2.7 on 2019-11-06 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('winecellar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shelf',
            old_name='description',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='shelf',
            name='uid',
        ),
        migrations.AddField(
            model_name='madefrom',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='madefrom',
            name='wine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='winecellar.Wine'),
        ),
    ]
